# Use the official Node.js image as the base image
FROM node:16

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./celestradepro/Backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the server files
COPY ./celestradepro/Backend .

# Expose the port the backend runs on
EXPOSE 3000

# Start the server
CMD ["node", "server.js"]
