version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Adjust this to the port your server listens on
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/FinanceDB

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
