version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27018:27017 # Map host port 27018 to container port 27017

  backend:
    image: vipv/kuber:${GITHUB_RUN_NUMBER}
    container_name: backend_container
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/FinanceDB

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    container_name: frontend_container
    ports:
      - 4200:4200
