version: '3.8'

services:
  app:
    image: vipv/combined-app:latest
    ports:
      - "4200:4200"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
