version: '3'
services:
  app:
    build: .
    ports:
      - "3003:3003"
    environment:
      - MONGO_URL=mongodb://mongo:27018
      - DB_NAME=FinanceDB
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27018:27018"
    volumes:
      - ./data:/data/db
