name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
      - staging  # Trigger for staging branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    # Set up Node.js for backend and frontend
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    # Install dependencies and build frontend
    - name: Build Frontend (Angular)
      run: |
        cd frontend
        npm install
        npm run build --prod

    # Package frontend files
    - name: Package Frontend
      run: |
        cd frontend
        mkdir -p ../deploy/public
        cp -R dist/* ../deploy/public

    # Install dependencies for backend
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install
        mkdir -p ../deploy
        cp -R * ../deploy

    # Deploy to production or staging slot
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'CelesContainerWebApp'
        slot-name: ${{ github.ref == 'refs/heads/staging' && 'staging' || 'production' }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./deploy
