name: Build and deploy Angular app with Node backend to Azure Web App - celestradepro

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

 

 # Start backend server
      - name: Start backend server
        run: |
          echo "Verifying Backend folder..."
          ls -R Backend

          cd Backend
          npm install
          npm install mongoose

          echo "Starting backend server..."
          nohup node server.js &  # Keep backend running in the background
        env:
          AZURE_COSMOS_CONNECTIONSTRING: "mongodb://celescontainerwebapp-server:Cd8bsmtPGb944jUTWSF6f03i9ZyuoYpKSNd14ZX7rrL5hM9yzcdZF6WidOZABiakigan29ihvSGtACDbgtLJdg==@celescontainerwebapp-server.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false"
          DB_NAME: 'test'
          PORT: 443