name: Deploy Angular Frontend to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Angular CLI and frontend dependencies
        run: |
          cd celestradepro
          npm install -g @angular/cli
          npm install
          npm install highcharts --save

      - name: Build Angular frontend
        run: |
          cd celestradepro
          npm run build --prod -- --output-path=www

      - name: Deploy Angular frontend to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'celweb'
          slot-name: 'Production'  # Use 'Production' unless a custom slot exists
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'celestradepro/www'
