name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          cd Celestradepro  # Navigate to the correct directory if needed
          npm install
          npm run build --if-present
        working-directory: ./Celestradepro  # This ensures npm commands are run in the right folder

      - name: Zip the application
        run: |
          cd Celestradepro  # Make sure to zip from the right folder
          zip -r release.zip .
        working-directory: ./Celestradepro

      - name: Upload the artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: Celestradepro/release.zip  # Adjusted path to make sure artifact is uploaded

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download the artifact from the build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip the artifact
        run: unzip release.zip

      - name: Set Cosmos DB Connection String
        run: |
          echo "COSMOSDB_CONNECTION_STRING=${{ secrets.COSMOSDB_CONNECTION_STRING }}" >> .env
          echo "COSMOS_DB_NAME=${{ secrets.COSMOS_DB_NAME }}" >> .env

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CelesContainerWebApp'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7EA540B6EFD640D89D465639D713F193 }}
