name: Build and deploy Angular app with Node backend to Azure Web App - celestradepro

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install frontend dependencies and build Angular app
      - name: Install Angular CLI and frontend dependencies
        run: |
          cd celestradepro
          npm install -g @angular/cli
          npm install -f
          npm install ws@latest @types/ws@latest -f

      # Modify TypeScript Files
      - name: Modify TypeScript Files
        run: |
          find . -type f -name '*.ts' -exec sed -i '/server?: HTTPServer<V> | HTTPSServer<V> | undefined;/s/^/\/\/ @ts-ignore\n/' {} \;

      # Build Angular app
      - name: Build Angular app
        working-directory: ./celestradepro
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          ng build --output-path=www

      # Install and build backend
      - name: Install backend dependencies and prepare for deployment
        working-directory: ./celestradepro/Backend
        run: |
          npm install -f
          npm install mongoose -f
          # Copy backend files to the www directory for deployment
          cp -r . ../www/Backend/

      # Upload artifact for deployment
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: celestradepro/www  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      # Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: www

      # Create startup script
      - name: Create startup command file
        run: |
          echo "cd /home/site/wwwroot" > startup.sh
          echo "npm install -g pm2" >> startup.sh
          echo "cd Backend && npm install" >> startup.sh
          echo "pm2 start server.js --no-daemon" >> startup.sh
          chmod +x startup.sh

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CelesContainerWebApp'
          package: www
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

