name: Build and deploy Angular app with Node backend to Azure Web App - celestradepro

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Angular CLI and frontend dependencies
      - name: Install Angular CLI and frontend dependencies
        run: |
          cd celestradepro
          npm install -g @angular/cli
          npm install

      # Build Angular app with output path set to 'www'
      - name: Build Angular app
        working-directory: ./celestradepro
        run: ng build --configuration production --output-path=Backend/www

      # Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./celestradepro/Backend
        run: npm install

      # Upload the backend with built frontend as an artifact
      - name: Upload combined app as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: combined-app
          path: ./celestradepro/Backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'staging'

    steps:
      # Download the combined frontend and backend artifact
      - name: Download combined app artifact
        uses: actions/download-artifact@v4
        with:
          name: combined-app
          path: ./

      # Deploy the combined backend and frontend to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CelesContainerWebApp'
          slot-name: 'staging'
          package: ./Backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
