name: Build and deploy Full-Stack App to Azure Web App - celweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # --- Build Angular Frontend ---
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install frontend dependencies and build
        run: |
          cd celestradepro
          npm install -g @angular/cli
          npm install
          npm run build --prod

      # --- Build Node.js Backend ---
      - name: Install backend dependencies
        run: |
          cd celestradepro/Backend
          npm install

      # --- Prepare deployment package ---
      - name: Prepare deployment zip
        run: |
          mkdir deploy
          cp -r celestradepro/Backend/* deploy/
          cp -r celestradepro/www deploy/frontend
          cd deploy
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fullstack-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fullstack-app

      - name: Unzip artifact
        run: unzip release.zip -d .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'celweb'                        # Make sure this matches your Azure App Service name
          slot-name: 'Production'                   # ⚠️ Use 'Production' unless your slot is truly named 'app'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B8C6C164795845FABD2D32A817EB58B9 }}
          package: .
