name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Azure Web App
        uses: actions/setup-node@v3
        with:
          app-name: 'CelesContainerWebApp'
          slot-name: 'staging'
          package: .  # Deploy the entire directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_STAGINGE }}