name: Build, Test, and Deploy Angular and Node.js

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # Step 3: Install dependencies for Angular and Node.js
      - name: Install Dependencies
        run: |
          npm install
          npm install highcharts
          npm uninstall igniteui-angular-charts igniteui-angular-core || true # Prevents failure if already uninstalled
          npm install igniteui-angular-charts igniteui-angular-core
        working-directory: ./celestradepro


      # Step 5: Modify TypeScript files (e.g., to avoid compilation errors or add fixes)
      - name: Modify TypeScript Files
        run: |
          find . -type f -name '*.ts' -exec sed -i '/server?: HTTPServer<V> | HTTPSServer<V> | undefined;/s/^/\/\/ @ts-ignore\n/' {} \;

      # Step 6: Build Angular application
      - name: Build Angular App
        run: |
          export NODE_OPTIONS=--max_old_space_size=8192
          npm run build
        working-directory: ./celestradepro

      # Step 7: Set up Docker Buildx for multi-platform builds (if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 8: Build Docker image for the application
      - name: Build Docker Image
        run: |
          docker build -t vipv/celes:${{ github.run_number }} -f ./Dockerfile .

      # Step 9: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          docker login -u vipv -p 9092897730

      # Step 10: Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push vipv/celes:${{ github.run_number }}

      # Step 11: Run Docker container with the newly pushed image
      - name: Run Docker Container
        run: |
          docker run -d -p 4200:4200 vipv/celes:${{ github.run_number }}
