name: Build and Deploy Node.js App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Step 3: Clean cache and install dependencies
      - name: Clean cache and install dependencies
        run: |
          npm cache clean --force
          npm install --legacy-peer-deps
          npm install highcharts
          npm install webpack webpack-cli --save-dev --legacy-peer-deps
        working-directory: ./celestradepro


      # Step 4: Build the Angular project
      - name: Build the Angular project
        run: npm run build --if-present
        working-directory: ./celestradepro

      # Step 5: Zip the application for deployment
      - name: Zip the application for deployment
        run: zip -r release.zip ./celestradepro

      # Step 6: Upload artifact for deployment
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Download the artifact from the build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Step 2: Unzip the artifact
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Step 3: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CelesContainerWebApp'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
