name: Build and deploy Angular app with Node backend to Azure Web App - celestradepro

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: 1  Install Angular CLI and frontend dependencies
        working-directory: ./celestradepro
        run: |
          npm install -g @angular/cli
          npm install -f
          npm install ws@latest @types/ws@latest -f

      - name: Modify TypeScript Files (if necessary)
        run: |
          find . -type f -name '*.ts' -exec sed -i '/server?: HTTPServer<V> | HTTPSServer<V> | undefined;/s/^/\/\/ @ts-ignore\n/' {} \;

      - name: Build Angular app
        working-directory: ./celestradepro
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          ng build --output-path=www

      - name: Upload frontend artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: celestradepro/www

      - name: Install backend dependencies
        working-directory: ./celestradepro/Backend
        run: |
          npm install -f
          npm install mongoose -f
          # Uncomment if needed: npm install socket.io -f

      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: ./celestradepro/Backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'staging'

    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-app
          path: www

      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app
          path: Backend

      # Optional: List files in deployment directory for debugging
      # - name: List files in deployment directory
      #   run: ls -R .

      - name: Deploy Angular to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CelesContainerWebApp'
          slot-name: 'staging'
          package: www
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CelesBackendWebApp'
          slot-name: 'staging'
          package: ./Backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

      - name: Install pm2 (if not already installed)
        run: |
          npm install -g pm2

      - name: Start backend server
        working-directory: ./Backend
        run: |
          echo "Starting backend server..."
          pm2 start server.js
          pm2 save