name: Build and deploy Angular app with Node backend to Azure Web App - celestradepro

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Ensure backend starts properly on Azure (use npm start)
      - name: Ensure backend starts after deployment
        run: |
          # Install backend dependencies
          cd ./Celestradepro/celestradepro/Backend  # Update path according to where Backend is in your deployed app
          npm install
          npm install mongoose

          # Start backend using the npm start script
          echo "Starting backend server..."
          npm start &  # Use npm start instead of nohup

