name: Build and deploy Angular app with Node backend to Azure Web App - celestradepro

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

 

      # Ensure backend starts after deployment
      - name: Start backend server
        run: |
          echo "Verifying backend directory structure..."
          ls -R .

          if [ -d "./www/Backend" ]; then
            cd ./www/Backend
          else
            echo "Backend directory not found! Exiting..."
            exit 1
          fi

          # Install dependencies
          npm install
          npm install mongoose

          # Start backend server
          echo "Starting backend server..."
          nohup npm start &  # Keep backend running in the background
        env:
          AZURE_COSMOS_CONNECTIONSTRING: "mongodb://celescontainerwebapp-server:Cd8bsmtPGb944jUTWSF6f03i9ZyuoYpKSNd14ZX7rrL5hM9yzcdZF6WidOZABiakigan29ihvSGtACDbgtLJdg==@celescontainerwebapp-server.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false"
          DB_NAME: 'test'
          PORT: 443
