name: Build, Test, and Deploy Angular and Node.js App

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies (Backend)
        run: npm install
        working-directory: ./celestradepro/Backend

      - name: Install Dependencies (Frontend)
        run: |
          npm install
          npm install highcharts
          npm uninstall igniteui-angular-charts igniteui-angular-core
          npm install igniteui-angular-charts igniteui-angular-core
        working-directory: ./celestradepro

      # Uncomment if you need to run tests
      # - name: Install Jest
      #   run: |
      #     npm install --save-dev jest @types/jest jest-preset-angular
      #   working-directory: ./celestradepro

      # - name: Run Jest Tests
      #   run: npm test
      #   working-directory: ./celestradepro
      #   env:
      #     CI: true

      - name: Modify TypeScript Files
        run: |
          find . -type f -name '*.ts' -exec sed -i '/server?: HTTPServer<V> | HTTPSServer<V> | undefined;/s/^/\/\/ @ts-ignore\n/' {} \;
        working-directory: ./celestradepro

      - name: Build Angular App
        run: |
          export NODE_OPTIONS=--max_old_space_size=4096
          npm run build -- --output-path=dist
        working-directory: ./celestradepro
        env:
          NG_BUILD_OPTIMIZATION: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Images
        run: |
          docker build -t vipv/kuber:${{ github.run_number }} -f ./Dockerfile.frontend .

      - name: Log in to Docker Hub
        run: |
          docker login -u vipv -p 9092897730

      - name: Push Docker Image
        run: |
          docker push vipv/kuber:${{ github.run_number }}

      - name: Cleanup Docker
        run: |
          docker-compose down
          docker system prune -a --volumes -f

      - name: Run Docker Compose
        run: |
          docker-compose up -d

      - name: Verify MongoDB Connection
        run: |
          docker exec -it backend_container mongo --host mongodb:27017 --eval "db.runCommand({ connectionStatus: 1 })"
