name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # --- Frontend Deployment ---
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Angular CLI and frontend dependencies
        run: |
          cd celestradepro
          npm install -g @angular/cli
          npm install -f
          npm install ws@latest @types/ws@latest -f
          npm install highcharts --save

      - name: Modify TypeScript Files (Optional)
        run: |
          cd celestradepro
          find . -type f -name '*.ts' -exec sed -i '/server?: HTTPServer<V> | HTTPSServer<V> | undefined;/s/^/\/\/ @ts-ignore\n/' {} \;

      - name: Build frontend
        run: |
          cd celestradepro
          npm install
          npm install webpack --save-dev
          npm run build --prod

      # --- Backend Deployment ---
      - name: Set up Node.js for backend
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install backend dependencies and MongoDB
        run: |
          cd celestradepro/Backend
          npm install
          npm install mongodb --save
          npm install ws@latest @types/ws@latest --save

      - name: Build and package backend
        run: |
          cd celestradepro/Backend
          npm run build  # Replace with 'tsc' or other build scripts if needed

      # --- Deployment to Azure Web App ---
      # Deploying the backend code to Azure Web App
      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CelesContainerWebApp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'celestradepro/Backend'  # Path to the backend folder

      # Deploying the frontend code to Azure Web App (same App Service)
      - name: Deploy Frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CelesContainerWebApp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'celestradepro/www'  # Path to the frontend build folder
