name: Build and deploy Angular app with Node backend to Azure Web App - celestradepro

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Angular CLI and frontend dependencies
      - name: Install Angular CLI and frontend dependencies
        run: |
          cd Celestradepro/celestradepro
          npm install -g @angular/cli
          npm install -f
          npm install ws@latest @types/ws@latest -f

      # Modify TypeScript Files for compatibility
      - name: Modify TypeScript Files
        run: |
          cd Celestradepro/celestradepro
          find . -type f -name '*.ts' -exec sed -i '/server?: HTTPServer<V> | HTTPSServer<V> | undefined;/s/^/\/\/ @ts-ignore\n/' {} \;

      # Build Angular app
      - name: Build Angular app
        working-directory: ./Celestradepro/celestradepro
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          ng build --output-path=www

      # Upload frontend artifact for deployment
      - name: Upload frontend artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: Celestradepro/celestradepro/www

      # Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./Celestradepro/celestradepro/Backend
        run: |
          npm install -f
          npm install mongoose -f

      # Upload backend artifact for deployment job
      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: Celestradepro/celestradepro/Backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'staging'

    steps:
      # Download frontend artifact
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-app
          path: www

      # Download backend artifact
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app
          path: Backend

      # Deploy Angular app to Azure Web App
      - name: Deploy Angular to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CelesContainerWebApp'
          slot-name: 'staging'
          package: www
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

      # Start backend server
      - name: Start backend server
        working-directory: ./Backend
        run: |
          echo "Starting backend server..."
          npm install
          npm install mongoose
          nohup node server.js > server.log 2>&1 &
          tail -f server.log
        env:
          AZURE_COSMOS_CONNECTIONSTRING: "mongodb://celescontainerwebapp-server:Cd8bsmtPGb944jUTWSF6f03i9ZyuoYpKSNd14ZX7rrL5hM9yzcdZF6WidOZABiakigan29ihvSGtACDbgtLJdg==@celescontainerwebapp-server.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false"
          DB_NAME: 'test'
          PORT: 443
